// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/SampleClase3.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class SampleClase3 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=12;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,SampleClase3.createAutomaton()));
      $line=13;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,SampleClase3.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,SampleClase3.class,"main",$line);
    }
  }
  public static IAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=18;
      Object Q=$fix(GCollections.asSet("s","q1","q2","r1","r2"));
      $line=21;
      Object \u03A3=$fix(GCollections.asSet('a','b'));
      $line=24;
      Object q_0=$fix("s");
      $line=27;
      Object F=$fix(GCollections.asSet("q1","r1"));
      $line=30;
      Object \u03B4=$fix(new Object[]{new Object[]{"s",'a',"q1"},new Object[]{"s",'b',"r1"},new Object[]{"q1",'a',"q1"},new Object[]{"q1",'b',"q2"},new Object[]{"q2",'a',"q1"},new Object[]{"q2",'b',"q2"},new Object[]{"r1",'b',"r1"},new Object[]{"r1",'a',"r2"},new Object[]{"r2",'b',"r1"},new Object[]{"r2",'a',"r2"}});
      $line=42;
      $result=$invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q_0,F,\u03B4});
      if (true) break $try;
      $line=43;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,SampleClase3.class,"createAutomaton",$line);
    }
    return $cast(IAutomaton.class,$result);
  }
}
