// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/SampleClase1.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class SampleClase1 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=10;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,SampleClase1.createAutomaton()));
      $line=11;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,SampleClase1.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,SampleClase1.class,"main",$line);
    }
  }
  public static IAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=16;
      Object Q=$fix(GCollections.asSet("q1","q2"));
      $line=19;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=22;
      Object q_0=$fix("q1");
      $line=25;
      Object F=$fix(GCollections.emptySet());
      $line=28;
      Object \u03B4=$fix(new Object[]{new Object[]{"q1",'0',"q1"},new Object[]{"q1",'1',"q2"},new Object[]{"q2",'0',"q1"},new Object[]{"q2",'1',"q2"}});
      $line=34;
      $result=$invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q_0,F,\u03B4});
      if (true) break $try;
      $line=35;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,SampleClase1.class,"createAutomaton",$line);
    }
    return $cast(IAutomaton.class,$result);
  }
}
